Add pipelines to repository
hoprnet/uHTTP-lib pull request #31
Opened 2024-09-13 14:20 UTC by ausias-armesto

2024-09-16 07:26 UTC, esterlus commented
Can we get the node version matrix? Or will that come later?

2024-09-17 08:28 UTC, esterlus requested changes
For me the biggest issue is, that deployment is documented good enough in the main README.md.

Can you update the relevant sections of the README accordingly?

2024-09-17 08:28 UTC, esterlus commented on .github/workflows/README.md
> +This document describes the GitHub workflows used in this project.
Any reason those should not be part of the main README? Or at least linked there?

2024-09-17 08:34 UTC, ausias-armesto commented on .github/workflows/README.md
> +This document describes the GitHub workflows used in this project.
I considered it as internal development process documentation, which is different from the generic repository documentation which is more oriented to show how to use the repository.
But I don't have a strong argument on this, I will add the link

2024-09-17 09:08 UTC, ausias-armesto commented
> Can we get the node version matrix? Or will that come later?

Implemented already

2024-09-17 09:12 UTC, ausias-armesto commented
> For me the biggest issue is, that deployment is documented good enough in the main README.md. This should also include the new Changelog handling.
> 
> Can you update the relevant sections of the README accordingly?

Changelog is auto-generated automatically from the PR merged into main. No need to do anything from the development side other than contribute always to main from a PR. The changelog will be included in the body of the Github  Release

2024-09-17 10:05 UTC, esterlus approved these changes
Let's try the new workflow then

2024-09-17 10:21 UTC, merged